en_acronyms_list = [(r'\bMRI\b', 'magnetic resonance image'),
                    (r'\bCT\b', 'computed tomography'),
                    (r'\bPET\b', 'positron emission tomography'),
                    (r'\bSPECT\b', 'single photon emission computed tomography'),
                    (r'\bUS\b', 'ultrasound'),
                    (r'\bALS\b', 'amyotrophic lateral sclerosis'),
                    (r'\bECG\b', 'electrocardiogram'),
                    (r'\bEKG\b', 'electrocardiogram'),
                    (r'\bEEG\b', 'electroencephalogram'),
                    (r'\bEMG\b', 'electromyogram'),
                    (r'\bHR\b', 'heart rate'),
                    (r'\bABX\b', 'antibiotics'),
                    (r'\bAF\b', 'atrial fibrillation'),
                    (r'\bXR\b', 'x ray'),
                    (r'\bBLS\b', 'basic life support'),
                    (r'\bBMD\b', 'bone mass density'),
                    (r'\bBMI\b', 'body mass index'),
                    (r'\bBP\b', 'blood pressure'),
                    (r'\bBx\b', 'biopsy'),
                    (r'\bCAD\b', 'coronary artery disease'),
                    (r'\bCAT\b', 'computed axial tomography'),
                    (r'\bCBF\b', 'cerebral blood flow'),
                    (r'\bCO2\b', 'carbon dioxide'),
                    (r'\bO2\b', 'oxygen'),
                    (r'\bH2O\b', 'water'),
                    (r'\bCV\b', 'cardiovascular'),
                    (r'\bDNA\b', 'deoxyribonucleic acid'),
                    (r'\bRNA\b', 'ribonucleic acid'),
                    (r'\bDx\b', 'diagnosis'),
                    (r'\bEOC\b', 'emergency operations center'),
                    (r'\bFX\b', 'fracture'),
                    (r'\bGI\b', 'gastrointestinal'),
                    (r'\bGP\b', 'general practitioner'),
                    (r'\bICU\b', 'intensive care unit'),
                    (r'\bIQ\b', 'intelligence quotient'),
                    (r'\bIT\b', 'information technology'),
                    (r'\bIV\b', 'intravenous'),
                    (r'\bLOF\b', 'loss of fluid'),
                    (r'\bLTC\b', 'long term care'),
                    (r'\bLV\b', 'left ventricle'),
                    (r'\bRV\b', 'right ventricle'),
                    (r'\bMG\b', 'milligram'),
                    (r'\bML\b', 'milliliter'),
                    (r'\bNIH\b', 'national institutes of health'),
                    (r'\bNM\b', 'neuromuscular'),
                    (r'\bOCD\b', 'obsessive compulsive disorder'),
                    (r'\bOT\b', 'occupational therapy'),
                    (r'\bPHS\b', 'public health service'),
                    (r'\bPPE\b', 'personal protective equipment'),
                    (r'\bQA\b', 'quality assurance'),
                    (r'\bQI\b', 'quality improvement'),
                    (r'\bRF\b', 'risk factor'),
                    (r'\bRx\b', 'treatment'),
                    (r'\bSSA\b', 'social security administration'),
                    (r'\bTB\b', 'tuberculosis'),
                    (r'\bTLC\b', 'total lung capacity'),
                    (r'\bVF\b', 'ventricular fibrillation'),
                    (r'\bWHO\b', 'world health organization'),
                    (r'\bMBA\b', 'Master of Business Administration'),
                    ]

es_acronyms_list = [(r'\bADN\b', 'ácido desoxirribonucleico'),
                    (r'\bARN\b', 'ácido ribonucleico'),
                    (r'\bACV\b', 'accidente cerebrovascular'),
                    (r'\bAEMPS\b', 'Agencia Española de Medicamentos y Productos Sanitarios'),
                    (r'\bAIOS\b', 'Asociación Española de Cirujanos'),
                    (r'\bCOPD\b', 'Enfermedad Pulmonar Obstructiva Crónica'),
                    (r'\bCTE\b', 'Traumatismo Craneoencefálico'),
                    (r'\bEPOC\b', 'Enfermedad Pulmonar Obstructiva Crónica'),
                    (r'\bGVA\b', 'Gasto Ventilatorio Asistido'),
                    (r'\bHEPA\b', 'Filtro de Aire de Partículas de Alta Eficiencia'),
                    (r'\bHIV\b', 'Virus de Inmunodeficiencia Humana'),
                    (r'\bIBV\b', 'Instituto de Biomecánica de Valencia'),
                    (r'\bINSALUD\b', 'Instituto Nacional de la Salud'),
                    (r'\bIRAS\b', 'Infecciones Respiratorias Agudas Severas'),
                    (r'\bIRSST\b', 'Instituto Regional de Seguridad y Salud en el Trabajo'),
                    (r'\bISO\b', 'Organización Internacional de Normalización'),
                    (r'\bMSPE\b', 'Informe de Evaluación del Progreso del Estudiante en Medicina'),
                    (r'\bNEUMO\b', 'Neumología'),
                    (r'\bOMS\b', 'Organización Mundial de la Salud'),
                    (r'\bOTAN\b', 'Organización del Tratado del Atlántico Norte'),
                    (r'\bPCR\b', 'Reacción en Cadena de la Polimerasa'),
                    (r'\bPOC\b', 'Punto de Atención'),
                    (r'\bSATSE\b', 'Sindicato de Enfermería'),
                    (r'\bSNS\b', 'Sistema Nacional de Salud'),
                    (r'\bSTEMI\b', 'Infarto de Miocardio con Elevación del Segmento ST'),
                    (r'\bSUAP\b', 'Servicio de Urgencia de Atención Primaria'),
                    (r'\bTAC\b', 'Tomografía Axial Computarizada'),
                    (r'\bTSI\b', 'Trabajador Social Sanitario'),
                    (r'\bUCI\b', 'Unidad de Cuidados Intensivos'),
                    (r'\bUCIN\b', 'Unidad de Cuidados Intensivos Neonatales'),
                    (r'\bUCP\b', 'Unidad de Cuidados Paliativos'),
                    (r'\bUVI\b', 'Unidad de Vigilancia Intensiva'),
                    (r'\bADE\b', 'Administración y Dirección de Empresas'),
                    (r'\bETSIT\b', 'Escuela Técnica Superior de Ingenieros de Telecomunicación'),
                    (r'\bGREM\b', 'Gestión de Recursos Humanos y Emprendimiento')
                    ]
